CRAB-44995: Add version declarations to the connector SDKs (Java)
seeq12/seeq-connector-sdk-java pull request #7
Opened 2024-12-10 21:50 UTC by lcollins-seeq

Updated the Java Connector SDK so the Connector binaries include the version number and minimum Seeq Link SDK version. 

---

**Takeaways**
N/A

---

### Merge Criteria

**Primary reviewer** @andre-rigon 
**Knowledge base** N/A - Handled by https://seeq.atlassian.net/browse/CRAB-46169
**Compatibility breaks** N/A 
**Security considerations** N/A
**Exploratory functional testing** Check out the branch and build it per the README.md instructions. Confirm that the build products contain the expected version information and that it can be updated as a user. 
**Regression testing** N/A
**Product Owner acceptance** @monstrorivas 
**Presentation slide/Release notes** N/A

2024-12-11 15:50 UTC, andre-rigon commented on mycompany-seeq-link-connector-myconnector/build.gradle.kts
> +val minimumSeeqLinkSdkVersion = "100.0.0.0"
I understand there is no released `100.0.x.x` version of the Link SDK in Java yet, but I think this CRAB won't be really complete until the minimum Link SDK declaration matches the version actually used as a dependency below. I think using different versions might be confusing for developers.

In the latest connector test framework there is a test called `testVersionDeclarations` that actually checks this.

2024-12-11 15:51 UTC, andre-rigon commented on mycompany-seeq-link-connector-myconnector/build.gradle.kts
I understand there is no released 100.0.x.x version of the Link SDK in Java yet, but I think this CRAB won't be really complete until the minimum Link SDK declaration matches the version actually used as a dependency below. I think using different versions might be confusing for developers.

In the latest connector test framework there is a test called testVersionDeclarations that actually checks this.

2024-12-11 17:50 UTC, andre-rigon commented on mycompany-seeq-link-connector-myconnector/build.gradle.kts
Thanks!

I think https://seeq.atlassian.net/browse/CRAB-46024 will allow us to release the new SDK version, so that's a good target.

2025-02-04 13:43 UTC, mar1u50 commented on README.md
> +   Agent Name field enter "Java Connector SDK Debugging Agent". Click Save and record the displayed One-Time Password
I think they will need to expand "Advanced" option. I think we describe that.

2025-02-04 13:45 UTC, mar1u50 commented on mycompany-seeq-link-connector-myconnector/build.gradle.kts
> +val minimumSeeqLinkSdkVersion = "100.0.0.0"
Hmm. Is it still ok to point to 100.0.0.0? I think we should point to an existing version.

2025-02-04 13:45 UTC, mar1u50 approved these changes
I wrote jsut a few  suggestions

2025-02-04 20:09 UTC, mar1u50 commented on mycompany-seeq-link-connector-myconnector/build.gradle.kts
> +    compileOnly("com.seeq.link:seeq-link-sdk:100.3.349")
How hard do you think it would be to extract this version into one single place? (not necessary in this PR but I think it would be great if we can do this easily).
Maybe we can have it in gradle settings or at least extract it in a variable here

2025-02-21 20:20 UTC, andre-rigon requested changes
The changes are looking great, @lcollins-seeq!

I started the test agent and it loaded the connector successfully, including the minimum SDK version. There was only a problem with the connector version currently having 4 numbers (see other comment). I also left some other very minor feedback.

Please let me know when ready and I'll test again and approve!

2025-02-21 20:20 UTC, andre-rigon commented on README.md
> +   Debugging Agent". Click Save and record the displayed One-Time Password value for use in the next step.
Since `Java Connector SDK Debugging Agent` is likely to be copy-pasted by the user and needs to be exact, what do you think about putting it in a single line, so no line breaks or (especially) indentation spaces are copy-pasted too? 
I'm mentioning this because initially I didn't notice the extra spaces when copy-pasting.

2025-02-21 20:22 UTC, andre-rigon commented on README.md
> +   Debugging Agent". Click Save and record the displayed One-Time Password value for use in the next step.
I just thought this happened because I was looking at the unrendered Markdown file, so if you think it's not important feel free to ignore!

2025-02-21 21:19 UTC, andre-rigon approved these changes
Exploratory testing notes:

- Started Seeq and followed the connector SDK README.md instructions to provision an agent ✅ 
- Started the agent with `./gradlew run` and it connected to Seeq. The logs show the correct connector and minimum Link SDK versions: ✅ 

```
INFO  2025-02-21T18:13:58.139-03:00 [Engage] com.seeq.link.agent.DefaultConnectorLoader - Loading candidate JAR: 'C:\Users\andrerigon\work\code\seeq-connector-sdk-java\mycompany-seeq-link-connector-myconnector\build\libs\mycompany-seeq-link-connector-myconnector-1.0.0.jar'
INFO  2025-02-21T18:13:58.151-03:00 [Engage] com.seeq.link.agent.DefaultConnectorLoader - Successfully loaded connector MyCompany MyConnector(version: 1.0.0, minimumSeeqLinkSdkVersion: 100.3.349, useIsolatedClassLoader: unspecified)
```

- The UI also shows those versions: ✅ 

![image](https://github.com/user-attachments/assets/4c5abcb9-1b57-41e8-a91f-ec155bb8e698)


- I was able to index and trend signals ✅ 
- Executed tests with `./gradlew test --rerun` and the passed ✅ 

Great work @lcollins-seeq, thanks for updating this project!

2025-02-21 21:34 UTC, merged